version: '2'

services:

  base:
    build:
      context: .
    image: 'developmentseed/sat-gbdx:latest'
    entrypoint: /bin/bash
    env_file: .env
    volumes:
      - '.:/home/geolambda/work'

  test:
    image: 'developmentseed/sat-gbdx:latest'
    entrypoint: bash -c 'pytest test/'
    env_file: .env
    volumes:
      - './test:/home/geolambda/test'
